-- =============================================================================
-- MIGRACIÓN: Centro de Notificaciones por cuenta (SSE multidispositivo)
-- -----------------------------------------------------------------------------
-- Añade la tabla NOTIFICACIONES, fuente de verdad única del centro de
-- notificaciones. La asociación es POR CUENTA (Trabajadores_idTrabajador), lo
-- que permite que todas las sesiones/instancias del mismo usuario (PC,
-- Electron, Android) se sincronicen vía SSE.
--
-- Idempotente: el runner verifica la existencia de cada objeto antes de crearlo.
-- =============================================================================

CREATE TABLE Notificaciones (
    IdNotificacion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    Tipo VARCHAR(12) NOT NULL,             -- success | warning | error | info
    Mensaje VARCHAR(500) NOT NULL,
    CreadoEn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (IdNotificacion),
    CONSTRAINT fk_Notificaciones_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION
);

CREATE DESCENDING INDEX IDX_Notificaciones_Trabajador_CreadoEn
    ON Notificaciones (Trabajadores_idTrabajador, CreadoEn);