-- =============================================================================
-- MIGRACIÓN: FechaInicio en Obras + vínculo a TRABAJO + SP_INSERTAR_OBRA ampliado
-- -----------------------------------------------------------------------------
-- 1. Crea la tabla TRABAJO (tipo de trabajo del cliente) si no existe.
-- 2. Añade la columna TRABAJOS_IDTRABAJO a Obras (vínculo al trabajo).
-- 3. Añade la columna FechaInicio (opcional) a Obras.
-- 4. Amplía SP_INSERTAR_OBRA para aceptar el trabajo y la fecha de inicio.
--
-- Idempotente: el runner (src/scripts/apply-obra-fecha-inicio-migration.js)
-- verifica cada objeto contra RDB$ antes de crearlo; el procedimiento se
-- re-crea con CREATE OR ALTER en cada ejecución.
-- =============================================================================

-- 1) Tabla TRABAJO (verificada contra RDB$RELATIONS)
-- CREATE TABLE TRABAJO (
--     idTrabajo INTEGER GENERATED BY DEFAULT AS IDENTITY,
--     Nombre VARCHAR(100) NOT NULL,
--     Descripcion BLOB SUB_TYPE TEXT,
--     Direccion BLOB SUB_TYPE TEXT,
--     FechaCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
--     Clientes_idCliente INTEGER NOT NULL,
--     PRIMARY KEY (idTrabajo),
--     CONSTRAINT fk_TRABAJO_Clientes1
--         FOREIGN KEY (Clientes_idCliente)
--         REFERENCES Clientes (idCliente)
--             ON DELETE NO ACTION
-- );

-- 2) Columna TRABAJOS_IDTRABAJO en Obras (verificada contra RDB$RELATION_FIELDS)
-- ALTER TABLE Obras ADD TRABAJOS_IDTRABAJO INTEGER;
-- ALTER TABLE Obras ADD CONSTRAINT fk_Obras_TRABAJO1
--     FOREIGN KEY (TRABAJOS_IDTRABAJO) REFERENCES TRABAJO (idTrabajo);

-- 3) Columna FechaInicio en Obras (verificada contra RDB$RELATION_FIELDS)
-- ALTER TABLE Obras ADD FechaInicio TIMESTAMP;

-- 4) SP_INSERTAR_OBRA ampliado (idempotente: CREATE OR ALTER)
CREATE OR ALTER PROCEDURE SP_INSERTAR_OBRA (
    pIdCliente INTEGER,
    pNombre    VARCHAR(100),
    pDireccion BLOB SUB_TYPE TEXT,
    pIdTrabajo INTEGER,
    pFechaInicio TIMESTAMP
)
RETURNS (
    oIdObra INTEGER
)
AS
BEGIN
    INSERT INTO Obras (Clientes_idCliente, Nombre, Direccion, TRABAJOS_IDTRABAJO, FechaInicio, EstadosObra_idEstadoObra)
    VALUES (:pIdCliente, :pNombre, :pDireccion, :pIdTrabajo, :pFechaInicio, 1)
    RETURNING idObra INTO :oIdObra;

    SUSPEND;
END