import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { appConfig } from './app/app.config';
import { provideIonicAngular } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import { registerIonicWebComponents } from './app/register-ionic-web-components';
import {
  searchOutline,
  personOutline,
  lockClosedOutline,
  eyeOutline,
  eyeOffOutline,
  alertCircleOutline,
  peopleOutline,
  constructOutline,
  cubeOutline,
  trashOutline,
  add,
  close,
  checkmarkCircle,
  closeCircle,
  informationCircle,
  warning,
  helpCircleOutline,
  chevronDownOutline,
  chevronBackOutline,
  settingsOutline,
  logOutOutline,
  notificationsOutline,
  checkmarkCircleOutline,
  timeOutline,
  calendarOutline,
  listOutline,
  copyOutline,
  personCircleOutline,
  albumsOutline,
  callOutline,
  cartOutline,
  checkmarkDoneCircleOutline,
  checkmarkDoneOutline,
  cloudOfflineOutline,
  imageOutline,
  layersOutline,
  locationOutline,
  navigateOutline,
  resizeOutline,
  sendOutline,
  shieldCheckmarkOutline,
  warningOutline,
  wifiOutline,
} from 'ionicons/icons';

addIcons({
  'search-outline': searchOutline,
  'person-outline': personOutline,
  'lock-closed-outline': lockClosedOutline,
  'eye-outline': eyeOutline,
  'eye-off-outline': eyeOffOutline,
  'alert-circle-outline': alertCircleOutline,
  'people-outline': peopleOutline,
  'construct-outline': constructOutline,
  'cube-outline': cubeOutline,
  'trash-outline': trashOutline,
  add,
  close,
  'checkmark-circle': checkmarkCircle,
  'close-circle': closeCircle,
  'information-circle': informationCircle,
  warning,
  'help-circle-outline': helpCircleOutline,
  'chevron-down-outline': chevronDownOutline,
  'chevron-back-outline': chevronBackOutline,
  'settings-outline': settingsOutline,
  'log-out-outline': logOutOutline,
  'notifications-outline': notificationsOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'time-outline': timeOutline,
  'calendar-outline': calendarOutline,
  'list-outline': listOutline,
  'copy-outline': copyOutline,
  'person-circle-outline': personCircleOutline,
  'albums-outline': albumsOutline,
  'call-outline': callOutline,
  'cart-outline': cartOutline,
  'checkmark-done-circle-outline': checkmarkDoneCircleOutline,
  'checkmark-done-outline': checkmarkDoneOutline,
  'cloud-offline-outline': cloudOfflineOutline,
  'image-outline': imageOutline,
  'layers-outline': layersOutline,
  'location-outline': locationOutline,
  'navigate-outline': navigateOutline,
  'resize-outline': resizeOutline,
  'send-outline': sendOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'warning-outline': warningOutline,
  'wifi-outline': wifiOutline,
});

registerIonicWebComponents();

const providers = [...appConfig.providers, provideIonicAngular()];

bootstrapApplication(AppComponent, { providers });