-- CREATE DATABASE 'SIGEHU.FDB'
-- USER 'SYSDBA'
-- PASSWORD 'masterkey';

-- -----------------------------------------------------
-- TABLAS CATALOGO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- TiposUsuarios
-- -----------------------------------------------------
CREATE TABLE TiposUsuarios (
    idTipoUsuario INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(20) NOT NULL,
    PRIMARY KEY (idTipoUsuario)
);

COMMIT;

INSERT INTO TiposUsuarios (Nombre) VALUES ('Propietario');
INSERT INTO TiposUsuarios (Nombre) VALUES ('Trabajador');

COMMIT;

-- -----------------------------------------------------
-- RegimenesFiscales
-- -----------------------------------------------------
CREATE TABLE RegimenesFiscales (
    idRegimenFiscal INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Codigo VARCHAR(3) NOT NULL,
    Descripcion VARCHAR(100) NOT NULL,
    CONSTRAINT PK_RegimenesFiscales PRIMARY KEY (idRegimenFiscal)
);

COMMIT;

CREATE UNIQUE INDEX Codigo_UNIQUE ON RegimenesFiscales(Codigo);

COMMIT;

INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('601', 'REGIMEN GENERAL DE LEY PERSONAS MORALES');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('602', 'RÉGIMEN SIMPLIFICADO DE LEY PERSONAS MORALES');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('603', 'PERSONAS MORALES CON FINES NO LUCRATIVOS');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('604', 'RÉGIMEN DE PEQUEÑOS CONTRIBUYENTES');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('605', 'RÉGIMEN DE SUELDOS Y SALARIOS E INGRESOS ASIMILADOS A SALARIOS');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('606', 'RÉGIMEN DE ARRENDAMIENTO');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('607', 'RÉGIMEN DE ENAJENACIÓN O ADQUISICIÓN DE BIENES');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('608', 'RÉGIMEN DE LOS DEMÁS INGRESOS');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('609', 'RÉGIMEN DE CONSOLIDACIÓN');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('610', 'RÉGIMEN RESIDENTES EN EL EXTRANJERO SIN ESTABLECIMIENTO PERMANENTE EN MÉXICO');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('611', 'RÉGIMEN DE INGRESOS POR DIVIDENDOS (SOCIOS Y ACCIONISTAS)');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('612', 'RÉGIMEN DE LAS PERSONAS FÍSICAS CON ACTIVIDADES EMPRESARIALES Y PROFESIONALES');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('613', 'RÉGIMEN INTERMEDIO DE LAS PERSONAS FÍSICAS CON ACTIVIDADES EMPRESARIALES');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('614', 'RÉGIMEN DE LOS INGRESOS POR INTERESES');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('615', 'RÉGIMEN DE LOS INGRESOS POR OBTENCIÓN DE PREMIOS');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('616', 'SIN OBLIGACIONES FISCALES');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('617', 'PEMEX');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('618', 'RÉGIMEN SIMPLIFICADO DE LEY PERSONAS FÍSICAS');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('619', 'INGRESOS POR LA OBTENCIÓN DE PRÉSTAMOS');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('620', 'SOCIEDADES COOPERATIVAS DE PRODUCCIÓN QUE OPTAN POR DIFERIR SUS INGRESOS');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('621', 'RÉGIMEN DE INCORPORACIÓN FISCAL');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('622', 'RÉGIMEN DE ACTIVIDADES AGRÍCOLAS, GANADERAS, SILVÍCOLAS Y PESQUERAS PM');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('623', 'RÉGIMEN DE OPCIONAL PARA GRUPOS DE SOCIEDADES');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('624', 'RÉGIMEN DE LOS COORDINADOS');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('625', 'RÉGIMEN DE LAS ACTIVIDADES EMPRESARIALES CON INGRESOS A TRAVÉS DE PLATAFORMAS TECNOLÓGICAS');
INSERT INTO RegimenesFiscales (Codigo, Descripcion) VALUES
('626', 'RÉGIMEN SIMPLIFICADO DE CONFIANZA');

COMMIT;

-- -----------------------------------------------------
-- UsosCFDI
-- -----------------------------------------------------
CREATE TABLE UsosCFDI (
    idUsoCFDI INTEGER GENERATED BY DEFAULT AS IDENTITY,
    UsoCFDI VARCHAR(5) NOT NULL,
    Descripcion VARCHAR(100) NOT NULL,
    CONSTRAINT PK_UsosCFDI PRIMARY KEY (idUsoCFDI)
);

COMMIT;

CREATE UNIQUE INDEX UsoCFDI_UNIQUE ON UsosCFDI(UsoCFDI);

COMMIT;

INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('G01', 'ADQUISICIÓN DE MERCANCÍAS');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('G02', 'DEVOLUCIONES, DESCUENTOS O BONIFICACIONES');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('G03', 'GASTOS EN GENERAL');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('I01', 'CONSTRUCCIONES');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('I02', 'MOBILIARIO Y EQUIPO DE OFICINA PARA INVERSIONES');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('I03', 'EQUIPO DE TRANSPORTE');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('I04', 'EQUIPO DE CÓMPUTO Y ACCESORIOS');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('I05', 'DADOS, TROQUELES, MOLDES, MATRICES Y HERRAMENTAL');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('I06', 'COMUNICACIONES TELEFÓNICAS');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('I07', 'COMUNICACIONES SATELITALES');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('I08', 'OTRA MAQUINARIA Y EQUIPO');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('D01', 'HONORARIOS MÉDICOS, DENTALES Y HOSPITALARIOS');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('D02', 'GASTOS MÉDICOS POR INCAPACIDAD O DISCAPACIDAD');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('D03', 'GASTOS FUNERALES');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('D04', 'DONATIVOS');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('D05', 'INTERESES REALES PAGADOS POR CRÉDITOS HIPOTECARIOS');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('D06', 'APORTACIONES VOLUNTARIAS AL SAR');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('D07', 'PRIMAS DE SEGUROS DE GASTOS MÉDICOS');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('D08', 'GASTOS DE TRANSPORTACIÓN ESCOLAR OBLIGATORIA');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('D09', 'DEPÓSITOS EN CUENTAS PARA EL AHORRO, PRIMAS DE PENSIONES');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('D10', 'PAGOS POR SERVICIOS EDUCATIVOS (COLEGIATURAS)');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('S01', 'SIN EFECTOS FISCALES');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('CP01', 'PAGOS');
INSERT INTO UsosCFDI (UsoCFDI, Descripcion) VALUES 
('CN01', 'NÓMINA');

COMMIT;

-- -----------------------------------------------------
-- EstadosObra
-- -----------------------------------------------------
CREATE TABLE EstadosObra (
    idEstadoObra INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(50) NOT NULL,
    Orden SMALLINT NOT NULL,
    PRIMARY KEY (idEstadoObra)
);

COMMIT;

INSERT INTO EstadosObra (Nombre, Orden) VALUES ('Solicitud recibida', 1);
INSERT INTO EstadosObra (Nombre, Orden) VALUES ('Levantamiento pendiente', 2);
INSERT INTO EstadosObra (Nombre, Orden) VALUES ('En fabricacion', 3);
INSERT INTO EstadosObra (Nombre, Orden) VALUES ('Instalacion programada', 4);
INSERT INTO EstadosObra (Nombre, Orden) VALUES ('Instalado', 5);
INSERT INTO EstadosObra (Nombre, Orden) VALUES ('Garantia', 6);
INSERT INTO EstadosObra (Nombre, Orden) VALUES ('Finalizado', 7);

COMMIT;

-- -----------------------------------------------------
-- Materiales
-- -----------------------------------------------------
CREATE TABLE Materiales (
    idMaterial INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(150) NOT NULL,
    UnidadMedida VARCHAR(20) NOT NULL,
    Descripcion BLOB SUB_TYPE TEXT,
    Activo BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (idMaterial)
);

COMMIT;

-- -----------------------------------------------------
-- TiposPago
-- -----------------------------------------------------
CREATE TABLE TiposPago (
    idTipoPago INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY (idTipoPago)
);

COMMIT;

INSERT INTO TiposPago (Nombre) VALUES ('Efectivo');
INSERT INTO TiposPago (Nombre) VALUES ('Transferencia');

COMMIT;

-- -----------------------------------------------------
-- FormasPago
-- -----------------------------------------------------
CREATE TABLE FormasPago (
    idFormaPago INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(50) NOT NULL,
    PRIMARY KEY (idFormaPago)
);

COMMIT;

INSERT INTO FormasPago (Nombre) VALUES ('Anticipo');
INSERT INTO FormasPago (Nombre) VALUES ('Parcial');
INSERT INTO FormasPago (Nombre) VALUES ('Liquidación');

COMMIT;

-- -----------------------------------------------------
-- CamposPermiso
-- -----------------------------------------------------
CREATE TABLE CamposPermiso (
    idCampoPermiso INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NombreCampo VARCHAR(50) NOT NULL,
    Descripcion BLOB SUB_TYPE TEXT,
    PRIMARY KEY (idCampoPermiso)
);

COMMIT;

INSERT INTO CamposPermiso (NombreCampo, Descripcion) VALUES
('direccion_instalacion', 'Direccion de instalacion de la obra');
INSERT INTO CamposPermiso (NombreCampo, Descripcion) VALUES
('telefono_cliente', 'Telefono del cliente vinculado a la obra');
INSERT INTO CamposPermiso (NombreCampo, Descripcion) VALUES
('notas_obra', 'Notas y observaciones internas de la obra');
INSERT INTO CamposPermiso (NombreCampo, Descripcion) VALUES
('fotos_referencia', 'Foto del modelo/referencia adjunta a la obra');
INSERT INTO CamposPermiso (NombreCampo, Descripcion) VALUES
('medidas', 'Medidas reales capturadas en levantamiento');
INSERT INTO CamposPermiso (NombreCampo, Descripcion) VALUES
('catalogo_proveedores', 'Acceso al catalogo de proveedores para compras');
INSERT INTO CamposPermiso (NombreCampo, Descripcion) VALUES
('subir_fotos', 'Permiso para adjuntar evidencias fotograficas');
INSERT INTO CamposPermiso (NombreCampo, Descripcion) VALUES
('confirmar_actividad', 'Permiso para confirmar la etapa asignada');

COMMIT;

-- -----------------------------------------------------
-- EstadosGarantia
-- -----------------------------------------------------
CREATE TABLE EstadosGarantia (
    idEstadoGarantia INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(20) NOT NULL,
    Orden SMALLINT NOT NULL,
    PRIMARY KEY (idEstadoGarantia)
);

COMMIT;

INSERT INTO EstadosGarantia (Nombre, Orden) VALUES ('Reportada', 1);
INSERT INTO EstadosGarantia (Nombre, Orden) VALUES ('En atencion', 2);
INSERT INTO EstadosGarantia (Nombre, Orden) VALUES ('Resuelta', 3);

COMMIT;

-- -----------------------------------------------------
-- Proveedores -- Recordar Permisos Granulares Proveedores
-- -----------------------------------------------------
CREATE TABLE Proveedores (
    idProveedor INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Nombre VARCHAR(100) NOT NULL,
    Direccion BLOB SUB_TYPE TEXT,
    Telefono VARCHAR(15),
    Correo VARCHAR(254),
    Notas BLOB SUB_TYPE TEXT,
    Activo BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (idProveedor)
);

COMMIT;

CREATE INDEX IDX_Proveedores_Nombre ON Proveedores (Nombre);

COMMIT;

-- -----------------------------------------------------
-- TABLAS PRINCIPALES
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Trabajadores
-- -----------------------------------------------------
CREATE TABLE Trabajadores (
    idTrabajador INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NombreUsuario VARCHAR(50) NOT NULL,
    Contra VARCHAR(100) NOT NULL, -- hash bcrypt
    NombreCompleto VARCHAR(100) NOT NULL,
    Telefono VARCHAR(15),
    TiposUsuarios_idTipoUsuario INTEGER NOT NULL,
    Activo BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (idTrabajador),
    CONSTRAINT fk_Trabajadores_TiposUsuarios1
        FOREIGN KEY (TiposUsuarios_idTipoUsuario)
        REFERENCES TiposUsuarios (idTipoUsuario)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_Trabajadores_TiposUsuarios1_idx ON Trabajadores(TiposUsuarios_idTipoUsuario);

COMMIT;

-- -----------------------------------------------------
-- Clientes
-- -----------------------------------------------------
CREATE TABLE Clientes (
    idCliente INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NombreCompleto VARCHAR(100) NOT NULL,
    Telefono VARCHAR(15) NOT NULL,
    Correo VARCHAR(254),
    Direccion BLOB SUB_TYPE TEXT,
    RFC VARCHAR(13),
    RegimenesFiscales_idRegimenFiscal INTEGER,
    CodigoPostal VARCHAR(5),
    UsosCFDI_idUsoCFDI INTEGER,
    Observaciones BLOB SUB_TYPE TEXT,
    Activo BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (idCliente),
    CONSTRAINT UQ_CLIENTES_RFC UNIQUE (RFC),
    CONSTRAINT fk_Clientes_RegimenesFiscales1
        FOREIGN KEY (RegimenesFiscales_idRegimenFiscal)
        REFERENCES RegimenesFiscales (idRegimenFiscal)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Clientes_UsosCFDI1
        FOREIGN KEY (UsosCFDI_idUsoCFDI)
        REFERENCES UsosCFDI (idUsoCFDI)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_Clientes_RegimenesFiscales1_idx ON Clientes(RegimenesFiscales_idRegimenFiscal);
CREATE INDEX fk_Clientes_UsosCFDI1_idx ON Clientes(UsosCFDI_idUsoCFDI);
CREATE INDEX IDX_Clientes_Nombre ON Clientes (NombreCompleto);

COMMIT;

-- -----------------------------------------------------
-- Obras
-- -----------------------------------------------------
CREATE TABLE Obras (
    idObra INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Clientes_idCliente INTEGER NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Direccion BLOB SUB_TYPE TEXT,
    Ancho DECIMAL(10,2),
    Alto DECIMAL(10,2),
    Profundidad DECIMAL(10,2),
    EstadosObra_idEstadoObra INTEGER NOT NULL,
    FechaCreacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FechaUltimaActualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Activo BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (idObra),
    CONSTRAINT fk_Obras_Clientes
        FOREIGN KEY (Clientes_idCliente)
        REFERENCES Clientes (idCliente)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Obras_EstadosObra1
        FOREIGN KEY (EstadosObra_idEstadoObra)
        REFERENCES EstadosObra (idEstadoObra)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_Obras_Clientes_idx ON Obras(Clientes_idCliente);
CREATE INDEX fk_Obras_EstadosObra1_idx ON Obras(EstadosObra_idEstadoObra);
CREATE INDEX IDX_Obras_Nombre ON Obras (Nombre);
CREATE INDEX IDX_Obras_Estado_Activo ON Obras (EstadosObra_idEstadoObra, Activo);

COMMIT;

SET TERM ^;
CREATE TRIGGER TR_OBRAS_BU
FOR Obras
ACTIVE BEFORE UPDATE
AS
BEGIN
    NEW.FechaUltimaActualizacion = CURRENT_TIMESTAMP;
END^
SET TERM ;^

COMMIT;

-- -----------------------------------------------------
-- FotosObras
-- -----------------------------------------------------
CREATE TABLE FotosObras (
    idFotoObra INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Obras_idObra INTEGER NOT NULL,
    EstadosObra_idEstadoObra INTEGER NOT NULL,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    RutaArchivo VARCHAR(300) NOT NULL,
    FechaCreacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idFotoObra),
    CONSTRAINT fk_Fotos_Obras1
        FOREIGN KEY (Obras_idObra)
        REFERENCES Obras (idObra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Fotos_EstadosObra1
        FOREIGN KEY (EstadosObra_idEstadoObra)
        REFERENCES EstadosObra (idEstadoObra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Fotos_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_Fotos_Obras1_idx ON FotosObras(Obras_idObra);
CREATE INDEX fk_Fotos_EstadosObra1_idx ON FotosObras(EstadosObra_idEstadoObra);
CREATE INDEX fk_Fotos_Trabajadores1_idx ON FotosObras(Trabajadores_idTrabajador);

COMMIT;

-- -----------------------------------------------------
-- Notas
-- -----------------------------------------------------
CREATE TABLE NotasObras (
    idNotaObra INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Obras_idObra INTEGER NOT NULL,
    EstadosObra_idEstadoObra INTEGER NOT NULL,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    Nota BLOB SUB_TYPE TEXT NOT NULL,
    FechaCreacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idNotaObra),
        CONSTRAINT fk_Notas_Obras1
        FOREIGN KEY (Obras_idObra)
        REFERENCES Obras (idObra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Notas_EstadosObra1
        FOREIGN KEY (EstadosObra_idEstadoObra)
        REFERENCES EstadosObra (idEstadoObra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Notas_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_Notas_Obras1_idx ON NotasObras(Obras_idObra);
CREATE INDEX fk_Notas_EstadosObra1_idx ON NotasObras(EstadosObra_idEstadoObra);
CREATE INDEX fk_Notas_Trabajadores1_idx ON NotasObras(Trabajadores_idTrabajador);

COMMIT;

-- -----------------------------------------------------
-- Obras_has_Materiales -> Materiales para la fabricacion de la obra
-- -----------------------------------------------------
CREATE TABLE Obras_has_Materiales (
    Obras_idObra INTEGER NOT NULL,
    Materiales_idMaterial INTEGER NOT NULL,
    Cantidad DECIMAL(10,2),
    Medida VARCHAR(20),
    Notas BLOB SUB_TYPE TEXT,
    PRIMARY KEY (Obras_idObra, Materiales_idMaterial),
        CONSTRAINT fk_Obras_has_Materiales_Obras1
        FOREIGN KEY (Obras_idObra)
        REFERENCES Obras (idObra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Obras_has_Materiales_Materiales1
        FOREIGN KEY (Materiales_idMaterial)
        REFERENCES Materiales (idMaterial)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_Obras_has_Materiales_Materiales1_idx ON Obras_has_Materiales(Materiales_idMaterial);
CREATE INDEX fk_Obras_has_Materiales_Obras1_idx ON Obras_has_Materiales(Obras_idObra);

COMMIT;

-- -----------------------------------------------------
-- Obras_has_Trabajadores -> Asignacion de trabajadores a cada estado de obra con fecha
-- -----------------------------------------------------
CREATE TABLE Obras_has_Trabajadores (
    idDetalleAsignacion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Obras_idObra INTEGER NOT NULL,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    EstadosObra_idEstadoObra INTEGER NOT NULL,
    FechaAsignacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idDetalleAsignacion),
    CONSTRAINT fk_Obras_has_Trabajadores_Obras1
        FOREIGN KEY (Obras_idObra)
        REFERENCES Obras (idObra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Obras_has_Trabajadores_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Obras_has_Trabajadores_EstadosObra1
        FOREIGN KEY (EstadosObra_idEstadoObra)
        REFERENCES EstadosObra (idEstadoObra)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_Obras_has_Trabajadores_Obras1_idx ON Obras_has_Trabajadores(Obras_idObra);
CREATE INDEX fk_Obras_has_Trabajadores_Trabajadores1_idx ON Obras_has_Trabajadores(Trabajadores_idTrabajador);
CREATE INDEX fk_Obras_has_Trabajadores_EstadosObra1_idx ON Obras_has_Trabajadores(EstadosObra_idEstadoObra);

COMMIT;

-- -----------------------------------------------------
-- DetallesPagos -> Permite registrar el tipo de pago, si fue anticipo, parcial o final, y el trabajador que lo registro
-- -----------------------------------------------------
CREATE TABLE DetallesPagos (
    idDetallePago INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Obras_idObra INTEGER NOT NULL,
    TiposPago_idTipoPago INTEGER NOT NULL,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    EstadosObra_idEstadoObra INTEGER NOT NULL,
    Monto DECIMAL(10,2) NOT NULL,
    FormasPago_idFormaPago INTEGER NOT NULL,
    FechaRegistro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idDetallePago),
    CONSTRAINT fk_DetallesPagos_Obras1
        FOREIGN KEY (Obras_idObra)
        REFERENCES Obras (idObra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_DetallesPagos_TiposPago1
        FOREIGN KEY (TiposPago_idTipoPago)
        REFERENCES TiposPago (idTipoPago)
            ON DELETE NO ACTION,
    CONSTRAINT fk_DetallesPagos_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION,
    CONSTRAINT fk_DetallesPagos_EstadosObra1
        FOREIGN KEY (EstadosObra_idEstadoObra)
        REFERENCES EstadosObra (idEstadoObra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_DetallesPagos_FormasPago1
        FOREIGN KEY (FormasPago_idFormaPago)
        REFERENCES FormasPago (idFormaPago)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_DetallesPagos_TiposPago1_idx ON DetallesPagos(TiposPago_idTipoPago);
CREATE INDEX fk_DetallesPagos_Obras1_idx ON DetallesPagos(Obras_idObra);
CREATE INDEX fk_DetallesPagos_Trabajadores1_idx ON DetallesPagos(Trabajadores_idTrabajador);
CREATE INDEX fk_DetallesPagos_EstadosObra1_idx ON DetallesPagos(EstadosObra_idEstadoObra);
CREATE INDEX fk_DetallesPagos_FormasPago1_idx ON DetallesPagos(FormasPago_idFormaPago);

COMMIT;

-- -----------------------------------------------------
-- PermisosGranulares
-- -----------------------------------------------------
CREATE TABLE PermisosGranularesObras (
    idPermisoGranularObra INTEGER GENERATED BY DEFAULT AS IDENTITY,
    CamposPermiso_idCampoPermiso INTEGER NOT NULL,
    Obras_idObra INTEGER NOT NULL,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    PRIMARY KEY (idPermisoGranularObra),
    CONSTRAINT UQ_PermisosGranularesObras UNIQUE (CamposPermiso_idCampoPermiso, Obras_idObra, Trabajadores_idTrabajador),
    CONSTRAINT fk_PermisosGranularesObras_CamposPermiso1
        FOREIGN KEY (CamposPermiso_idCampoPermiso)
        REFERENCES CamposPermiso (idCampoPermiso)
            ON DELETE NO ACTION,
    CONSTRAINT fk_PermisosGranularesObras_Obras1
        FOREIGN KEY (Obras_idObra)
        REFERENCES Obras (idObra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_PermisosGranularesObras_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_PermisosGranularesObras_CamposPermiso1_idx ON PermisosGranularesObras(CamposPermiso_idCampoPermiso);
CREATE INDEX fk_PermisosGranularesObras_Obras1_idx ON PermisosGranularesObras(Obras_idObra);
CREATE INDEX fk_PermisosGranularesObras_Trabajadores1_idx ON PermisosGranularesObras(Trabajadores_idTrabajador);

COMMIT;

-- -----------------------------------------------------
-- Proveedores_has_Materiales -> Materiales que provee un proveedor
-- -----------------------------------------------------
CREATE TABLE Proveedores_has_Materiales (
    Proveedores_idProveedor INTEGER NOT NULL,
    Materiales_idMaterial INTEGER NOT NULL,
    PrecioUnitario DECIMAL(10,2), -- Recordar que el precio puede cambiar con el tiempo
    Notas BLOB SUB_TYPE TEXT,
    PRIMARY KEY (Proveedores_idProveedor, Materiales_idMaterial),
    CONSTRAINT fk_Proveedores_has_Materiales_Proveedores1
        FOREIGN KEY (Proveedores_idProveedor)
        REFERENCES Proveedores (idProveedor)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Proveedores_has_Materiales_Materiales1
        FOREIGN KEY (Materiales_idMaterial)
        REFERENCES Materiales (idMaterial)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_Proveedores_has_Materiales_Materiales1_idx ON Proveedores_has_Materiales(Materiales_idMaterial);
CREATE INDEX fk_Proveedores_has_Materiales_Proveedores1_idx ON Proveedores_has_Materiales(Proveedores_idProveedor);

COMMIT;

-- -----------------------------------------------------
-- Compras
-- -----------------------------------------------------
CREATE TABLE Compras (
    idCompra INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    FechaCompra TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Notas BLOB SUB_TYPE TEXT,
    Activo BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (idCompra),
    CONSTRAINT fk_Compras_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_Compras_Trabajadores1_idx ON Compras(Trabajadores_idTrabajador);

COMMIT;

-- -----------------------------------------------------
-- DetallesCompras -> Relaciona las compras con los proveedores y materiales que se compraron
-- -----------------------------------------------------
CREATE TABLE DetallesCompras (
    idDetalleCompra INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Compras_idCompra INTEGER NOT NULL,
    Proveedores_has_Materiales_Proveedores_idProveedor INTEGER NOT NULL,
    Cantidad DECIMAL(10,2) NOT NULL,
    Medida VARCHAR(20),
    Proveedores_has_Materiales_Materiales_idMaterial INTEGER NOT NULL,
    PRIMARY KEY (idDetalleCompra),
    CONSTRAINT fk_DetallesCompras_Compras1
        FOREIGN KEY (Compras_idCompra)
        REFERENCES Compras (idCompra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_DetallesCompras_Proveedores_has_Materiales1
        FOREIGN KEY (Proveedores_has_Materiales_Proveedores_idProveedor , Proveedores_has_Materiales_Materiales_idMaterial)
        REFERENCES Proveedores_has_Materiales (Proveedores_idProveedor , Materiales_idMaterial)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_DetallesCompras_Proveedores_has_Materiales1_idx ON DetallesCompras(Proveedores_has_Materiales_Proveedores_idProveedor, Proveedores_has_Materiales_Materiales_idMaterial);
CREATE INDEX fk_DetallesCompras_Compras1_idx ON DetallesCompras(Compras_idCompra);

COMMIT;

-- -----------------------------------------------------
-- Garantias Creo que tambien ocupa sus propias notas
-- -----------------------------------------------------
CREATE TABLE Garantias (
    idGarantia INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Obras_idObra INTEGER NOT NULL,
    Descripcion BLOB SUB_TYPE TEXT,
    FechaCreacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    EstadosGarantia_idEstadoGarantia INTEGER NOT NULL,
    FechaUltimaActualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DescripcionResolucion BLOB SUB_TYPE TEXT,
    Activo BOOLEAN DEFAULT TRUE NOT NULL,
    PRIMARY KEY (idGarantia),
    CONSTRAINT fk_Garantias_EstadosGarantia1
        FOREIGN KEY (EstadosGarantia_idEstadoGarantia)
        REFERENCES EstadosGarantia (idEstadoGarantia)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Garantias_Obras1
        FOREIGN KEY (Obras_idObra)
        REFERENCES Obras (idObra)
            ON DELETE NO ACTION,
    CONSTRAINT fk_Garantias_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
            REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_Garantias_EstadosGarantia1_idx ON Garantias(EstadosGarantia_idEstadoGarantia);
CREATE INDEX fk_Garantias_Obras1_idx ON Garantias(Obras_idObra);
CREATE INDEX fk_Garantias_Trabajadores1_idx ON Garantias(Trabajadores_idTrabajador);

COMMIT;

SET TERM ^;
CREATE TRIGGER TR_GARANTIAS_BU
FOR Garantias
ACTIVE BEFORE UPDATE
AS
BEGIN
    NEW.FechaUltimaActualizacion = CURRENT_TIMESTAMP;
END^
SET TERM ;^

COMMIT;

-- -----------------------------------------------------
-- FotosGarantias
-- -----------------------------------------------------
CREATE TABLE FotosGarantias (
    idFotoGarantia INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Garantias_idGarantia INTEGER NOT NULL,
    EstadosGarantia_idEstadoGarantia INTEGER NOT NULL,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    RutaArchivo VARCHAR(300) NOT NULL,
    FechaCreacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idFotoGarantia),
    CONSTRAINT fk_FotosGarantias_Garantias1
        FOREIGN KEY (Garantias_idGarantia)
        REFERENCES Garantias (idGarantia)
            ON DELETE NO ACTION,
    CONSTRAINT fk_FotosGarantias_EstadosGarantia1
        FOREIGN KEY (EstadosGarantia_idEstadoGarantia)
        REFERENCES EstadosGarantia (idEstadoGarantia)
            ON DELETE NO ACTION,
    CONSTRAINT fk_FotosGarantias_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_FotosGarantias_Garantias1_idx ON FotosGarantias(Garantias_idGarantia);
CREATE INDEX fk_FotosGarantias_EstadosGarantia1_idx ON FotosGarantias(EstadosGarantia_idEstadoGarantia);
CREATE INDEX fk_FotosGarantias_Trabajadores1_idx ON FotosGarantias(Trabajadores_idTrabajador);

COMMIT;

-- -----------------------------------------------------
-- NotasGarantias
-- -----------------------------------------------------
CREATE TABLE NotasGarantias (
    idNotaGarantia INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Garantias_idGarantia INTEGER NOT NULL,
    EstadosGarantia_idEstadoGarantia INTEGER NOT NULL,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    Nota BLOB SUB_TYPE TEXT NOT NULL,
    FechaCreacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (idNotaGarantia),
    CONSTRAINT fk_NotasGarantias_Garantias1
        FOREIGN KEY (Garantias_idGarantia)
        REFERENCES Garantias (idGarantia)
            ON DELETE NO ACTION,
    CONSTRAINT fk_NotasGarantias_EstadosGarantia1
        FOREIGN KEY (EstadosGarantia_idEstadoGarantia)
        REFERENCES EstadosGarantia (idEstadoGarantia)
            ON DELETE NO ACTION,
    CONSTRAINT fk_NotasGarantias_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_NotasGarantias_Garantias1_idx ON NotasGarantias(Garantias_idGarantia);
CREATE INDEX fk_NotasGarantias_EstadosGarantia1_idx ON NotasGarantias(EstadosGarantia_idEstadoGarantia);
CREATE INDEX fk_NotasGarantias_Trabajadores1_idx ON NotasGarantias(Trabajadores_idTrabajador);

COMMIT;

-- -----------------------------------------------------
-- PermisosGranularesGarantias
-- -----------------------------------------------------
CREATE TABLE PermisosGranularesGarantias (
    idPermisoGranularGarantia INTEGER GENERATED BY DEFAULT AS IDENTITY,
    CamposPermiso_idCampoPermiso INTEGER NOT NULL,
    Garantias_idGarantia INTEGER NOT NULL,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    PRIMARY KEY (idPermisoGranularGarantia),
    CONSTRAINT fk_PermisosGranularesGarantias_CamposPermiso1
        FOREIGN KEY (CamposPermiso_idCampoPermiso)
        REFERENCES CamposPermiso (idCampoPermiso)
            ON DELETE NO ACTION,
    CONSTRAINT fk_PermisosGranularesGarantias_Garantias1
        FOREIGN KEY (Garantias_idGarantia)
        REFERENCES Garantias (idGarantia)
            ON DELETE NO ACTION,
    CONSTRAINT fk_PermisosGranularesGarantias_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION
);

COMMIT;

CREATE INDEX fk_PermisosGranularesGarantias_CamposPermiso1_idx ON PermisosGranularesGarantias(CamposPermiso_idCampoPermiso);
CREATE INDEX fk_PermisosGranularesGarantias_Garantias1_idx ON PermisosGranularesGarantias(Garantias_idGarantia);
CREATE INDEX fk_PermisosGranularesGarantias_Trabajadores1_idx ON PermisosGranularesGarantias(Trabajadores_idTrabajador);

COMMIT;

-- -----------------------------------------------------
-- Auditorias
-- -----------------------------------------------------
CREATE TABLE Auditorias (
    idAuditoria INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Trabajadores_idTrabajador INTEGER NOT NULL,
    Fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Tabla VARCHAR(50) NOT NULL,
    Accion VARCHAR(20) NOT NULL,
    Descripcion BLOB SUB_TYPE TEXT,
    RegistroAfectado VARCHAR(50) NOT NULL,
    CONSTRAINT fk_Auditorias_Trabajadores1
        FOREIGN KEY (Trabajadores_idTrabajador)
        REFERENCES Trabajadores (idTrabajador)
            ON DELETE NO ACTION,
    PRIMARY KEY (idAuditoria)
);

COMMIT;

CREATE INDEX IDX_Auditorias_Fecha ON Auditorias (Fecha);
CREATE INDEX IDX_Auditorias_Tabla_Accion ON Auditorias (Tabla, Accion);

COMMIT;

-- -----------------------------------------------------
-- AuditoriasDetalles -> Aplica para actualizaciones
-- -----------------------------------------------------
CREATE TABLE AuditoriasDetalles (
    idAuditoriaDetalle INTEGER GENERATED BY DEFAULT AS IDENTITY,
    Auditorias_idAuditoria INTEGER NOT NULL,
    Campo VARCHAR(50) NOT NULL,
    ValorAnterior BLOB SUB_TYPE TEXT,
    ValorNuevo BLOB SUB_TYPE TEXT,
    PRIMARY KEY (idAuditoriaDetalle),
    CONSTRAINT fk_AuditoriasDetalles_Auditorias1
        FOREIGN KEY (Auditorias_idAuditoria)
        REFERENCES Auditorias (idAuditoria)
            ON DELETE NO ACTION
);

COMMIT;

-- -----------------------------------------------------
-- Triggers para auditorias
-- -----------------------------------------------------

SET TERM ^;

-- Trabajadores - INSERT
CREATE OR ALTER TRIGGER TR_Auditorias_Trabajadores_AI
FOR Trabajadores
ACTIVE AFTER INSERT
POSITION 0
AS
    DECLARE VARIABLE vidAuditoria INTEGER;
    DECLARE VARIABLE vUsuarioCtx VARCHAR(10);
BEGIN
    -- Leer el idTrabajador que el backend guardó en el contexto de sesión.
    -- El backend debe llamar: SELECT RDB$SET_CONTEXT('USER_SESSION','CURRENT_USER_ID', :id) FROM RDB$DATABASE
    -- antes de cualquier INSERT/UPDATE.
    vUsuarioCtx = CAST(RDB$GET_CONTEXT('USER_SESSION', 'CURRENT_USER_ID') AS VARCHAR(10));

    INSERT INTO Auditorias (Trabajadores_idTrabajador, Tabla, Accion, Descripcion, RegistroAfectado)
    VALUES (
        COALESCE(CAST(vUsuarioCtx AS INTEGER), 1),
        'Trabajadores',
        'INSERT',
        'Se creó el trabajador: ' || NEW.NombreUsuario || '.',
        CAST(NEW.idTrabajador AS VARCHAR(50))
    )
    RETURNING idAuditoria INTO :vidAuditoria;
END^

-- Clientes - INSERT
CREATE OR ALTER TRIGGER TR_Auditorias_Clientes_AI
FOR Clientes
ACTIVE AFTER INSERT
POSITION 0
AS
    DECLARE VARIABLE vidAuditoria INTEGER;
    DECLARE VARIABLE vUsuarioCtx VARCHAR(10);
BEGIN
    vUsuarioCtx = CAST(RDB$GET_CONTEXT('USER_SESSION', 'CURRENT_USER_ID') AS VARCHAR(10));

    INSERT INTO Auditorias (Trabajadores_idTrabajador, Tabla, Accion, Descripcion, RegistroAfectado)
    VALUES (
        COALESCE(CAST(vUsuarioCtx AS INTEGER), 1),
        'Clientes',
        'INSERT',
        'Se creó el cliente: ' || NEW.NombreCompleto || '.',
        CAST(NEW.idCliente AS VARCHAR(50))
    );
END^

-- Obras - INSERT
CREATE OR ALTER TRIGGER TR_Auditorias_Obras_AI
FOR Obras
ACTIVE AFTER INSERT
POSITION 0
AS
    DECLARE VARIABLE vUsuarioCtx VARCHAR(10);
BEGIN
    vUsuarioCtx = CAST(RDB$GET_CONTEXT('USER_SESSION', 'CURRENT_USER_ID') AS VARCHAR(10));

    INSERT INTO Auditorias (Trabajadores_idTrabajador, Tabla, Accion, Descripcion, RegistroAfectado)
    VALUES (
        COALESCE(CAST(vUsuarioCtx AS INTEGER), 1),
        'Obras',
        'INSERT',
        'Se creó la obra: ' || NEW.Nombre || '.',
        CAST(NEW.idObra AS VARCHAR(50))
    );
END^

-- Proveedores - INSERT
CREATE OR ALTER TRIGGER TR_Auditorias_Proveedores_AI
FOR Proveedores
ACTIVE AFTER INSERT
POSITION 0
AS
    DECLARE VARIABLE vUsuarioCtx VARCHAR(10);
BEGIN
    vUsuarioCtx = CAST(RDB$GET_CONTEXT('USER_SESSION', 'CURRENT_USER_ID') AS VARCHAR(10));

    INSERT INTO Auditorias (Trabajadores_idTrabajador, Tabla, Accion, Descripcion, RegistroAfectado)
    VALUES (
        COALESCE(CAST(vUsuarioCtx AS INTEGER), 1),
        'Proveedores',
        'INSERT',
        'Se creó el proveedor: ' || NEW.Nombre || '.',
        CAST(NEW.idProveedor AS VARCHAR(50))
    );
END^

-- Materiales - INSERT
CREATE OR ALTER TRIGGER TR_Auditorias_Materiales_AI
FOR Materiales
ACTIVE AFTER INSERT
POSITION 0
AS
    DECLARE VARIABLE vUsuarioCtx VARCHAR(10);
BEGIN
    vUsuarioCtx = CAST(RDB$GET_CONTEXT('USER_SESSION', 'CURRENT_USER_ID') AS VARCHAR(10));

    INSERT INTO Auditorias (Trabajadores_idTrabajador, Tabla, Accion, Descripcion, RegistroAfectado)
    VALUES (
        COALESCE(CAST(vUsuarioCtx AS INTEGER), 1),
        'Materiales', 'INSERT',
        'Se creó el material: ' || NEW.Nombre || '.',
        CAST(NEW.idMaterial AS VARCHAR(50))
    );
END^

-- Garantias - INSERT
CREATE OR ALTER TRIGGER TR_Auditorias_Garantias_AI
FOR Garantias
ACTIVE AFTER INSERT
POSITION 0
AS
    DECLARE VARIABLE vUsuarioCtx VARCHAR(10);
BEGIN
    vUsuarioCtx = CAST(RDB$GET_CONTEXT('USER_SESSION', 'CURRENT_USER_ID') AS VARCHAR(10));

    INSERT INTO Auditorias (Trabajadores_idTrabajador, Tabla, Accion, Descripcion, RegistroAfectado)
    VALUES (
        COALESCE(CAST(vUsuarioCtx AS INTEGER), 1),
        'Garantias', 'INSERT',
        'Se abrió garantía para la obra id: ' || CAST(NEW.Obras_idObra AS VARCHAR(10)) || '.',
        CAST(NEW.idGarantia AS VARCHAR(50))
    );
END^

-- Compras - INSERT
CREATE OR ALTER TRIGGER TR_Auditorias_Compras_AI
FOR Compras
ACTIVE AFTER INSERT
POSITION 0
AS
    DECLARE VARIABLE vUsuarioCtx VARCHAR(10);
BEGIN
    vUsuarioCtx = CAST(RDB$GET_CONTEXT('USER_SESSION', 'CURRENT_USER_ID') AS VARCHAR(10));

    INSERT INTO Auditorias (Trabajadores_idTrabajador, Tabla, Accion, Descripcion, RegistroAfectado)
    VALUES (
        COALESCE(CAST(vUsuarioCtx AS INTEGER), 1),
        'Compras', 'INSERT',
        'Se registró una compra por el trabajador id: ' || CAST(NEW.Trabajadores_idTrabajador AS VARCHAR(10)) || '.',
        CAST(NEW.idCompra AS VARCHAR(50))
    );
END^

-- PermisosGranularesObras - INSERT (para auditar asignaciones de permisos)
CREATE OR ALTER TRIGGER TR_Auditorias_PermisosObras_AI
FOR PermisosGranularesObras
ACTIVE AFTER INSERT
POSITION 0
AS
    DECLARE VARIABLE vUsuarioCtx VARCHAR(10);
    DECLARE VARIABLE vCampo VARCHAR(50);
BEGIN
    vUsuarioCtx = CAST(RDB$GET_CONTEXT('USER_SESSION', 'CURRENT_USER_ID') AS VARCHAR(10));

    SELECT NombreCampo FROM CamposPermiso WHERE idCampoPermiso = NEW.CamposPermiso_idCampoPermiso
    INTO :vCampo;

    INSERT INTO Auditorias (Trabajadores_idTrabajador, Tabla, Accion, Descripcion, RegistroAfectado)
    VALUES (
        COALESCE(CAST(vUsuarioCtx AS INTEGER), 1),
        'PermisosGranularesObras', 'INSERT',
        'Se otorgó permiso "' || vCampo || '" al trabajador id: '
            || CAST(NEW.Trabajadores_idTrabajador AS VARCHAR(10))
            || ' en obra id: ' || CAST(NEW.Obras_idObra AS VARCHAR(10)) || '.',
        CAST(NEW.idPermisoGranularObra AS VARCHAR(50))
    );
END^

-- PermisosGranularesObras - DELETE (para auditar revocación de permisos)
CREATE OR ALTER TRIGGER TR_Auditorias_PermisosObras_AD
FOR PermisosGranularesObras
ACTIVE AFTER DELETE
POSITION 0
AS
    DECLARE VARIABLE vUsuarioCtx VARCHAR(10);
    DECLARE VARIABLE vCampo VARCHAR(50);
BEGIN
    vUsuarioCtx = CAST(RDB$GET_CONTEXT('USER_SESSION', 'CURRENT_USER_ID') AS VARCHAR(10));

    SELECT NombreCampo FROM CamposPermiso WHERE idCampoPermiso = OLD.CamposPermiso_idCampoPermiso
    INTO :vCampo;

    INSERT INTO Auditorias (Trabajadores_idTrabajador, Tabla, Accion, Descripcion, RegistroAfectado)
    VALUES (
        COALESCE(CAST(vUsuarioCtx AS INTEGER), 1),
        'PermisosGranularesObras', 'DELETE',
        'Se revocó permiso "' || vCampo || '" al trabajador id: '
            || CAST(OLD.Trabajadores_idTrabajador AS VARCHAR(10))
            || ' en obra id: ' || CAST(OLD.Obras_idObra AS VARCHAR(10)) || '.',
        CAST(OLD.idPermisoGranularObra AS VARCHAR(50))
    );
END^

SET TERM ;^


-- =============================================================================
-- SECCIÓN 4: PROCEDIMIENTOS ALMACENADOS
-- =============================================================================

SET TERM ^;

-- -----------------------------------------------------------------------------
-- SP_INSERTAR_PROVEEDOR_CON_MATERIALES
-- Recibe los datos del proveedor y un listado de idMaterial (separados por coma
-- o en llamadas iteradas desde Node).  Se llama con EXECUTE PROCEDURE.
--
-- NOTA: Firebird no soporta arrays como parámetros de entrada, así que la
-- estrategia correcta desde Node es:
--   1. EXECUTE PROCEDURE SP_INSERTAR_PROVEEDOR(...)       -> obtiene idProveedor
--   2. Loop en Node: EXECUTE PROCEDURE SP_VINCULAR_MATERIAL_PROVEEDOR(id, idMat, precio, notas)
-- -----------------------------------------------------------------------------

--ALTER TABLE AUDITORIAS 
--ALTER idAuditoria
--RESTART WITH 2;

CREATE OR ALTER PROCEDURE SP_INSERTAR_TRABAJADOR (
    tUsuario VARCHAR(50),
    tContra VARCHAR(100),
    tNombre VARCHAR(100),
    tTelefono VARCHAR(15),
    tTipo INTEGER
)
RETURNS (
    oIdTrabajador INTEGER
)
AS
BEGIN
    INSERT INTO Trabajadores (NombreUsuario, Contra, NombreCompleto, Telefono, TiposUsuarios_idTipoUsuario)
    VALUES (:tUsuario, :tContra, :tNombre, :tTelefono, :tTipo)
    RETURNING idTrabajador INTO :oIdTrabajador;

    SUSPEND;
END^

CREATE OR ALTER PROCEDURE SP_INSERTAR_PROVEEDOR (
    pNombre     VARCHAR(100),
    pDireccion  BLOB SUB_TYPE TEXT,
    pTelefono   VARCHAR(15),
    pCorreo     VARCHAR(254),
    pNotas      BLOB SUB_TYPE TEXT
)
RETURNS (
    oIdProveedor INTEGER
)
AS
BEGIN
    INSERT INTO Proveedores (Nombre, Direccion, Telefono, Correo, Notas)
    VALUES (:pNombre, :pDireccion, :pTelefono, :pCorreo, :pNotas)
    RETURNING idProveedor INTO :oIdProveedor;

    SUSPEND;
END^

-- -----------------------------------------------------------------------------
-- SP_ACTUALIZAR_PROVEEDOR
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_ACTUALIZAR_PROVEEDOR (
    pIdProveedor INTEGER,
    pNombre      VARCHAR(100),
    pDireccion   BLOB SUB_TYPE TEXT,
    pTelefono    VARCHAR(15),
    pCorreo      VARCHAR(254),
    pNotas       BLOB SUB_TYPE TEXT
)
AS
BEGIN
    UPDATE Proveedores
    SET Nombre    = :pNombre,
        Direccion = :pDireccion,
        Telefono  = :pTelefono,
        Correo    = :pCorreo,
        Notas     = :pNotas
    WHERE idProveedor = :pIdProveedor;
END^

-- -----------------------------------------------------------------------------
-- SP_VINCULAR_MATERIAL_PROVEEDOR
-- Vincula un material existente a un proveedor con precio y notas.
-- Usa UPDATE OR INSERT para manejar tanto creación como actualización de precio.
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_VINCULAR_MATERIAL_PROVEEDOR (
    pIdProveedor    INTEGER,
    pIdMaterial     INTEGER,
    pPrecioUnitario DECIMAL(10,2),
    pNotas          BLOB SUB_TYPE TEXT
)
AS
BEGIN
    UPDATE OR INSERT INTO Proveedores_has_Materiales
        (Proveedores_idProveedor, Materiales_idMaterial, PrecioUnitario, Notas)
    VALUES
        (:pIdProveedor, :pIdMaterial, :pPrecioUnitario, :pNotas)
    MATCHING (Proveedores_idProveedor, Materiales_idMaterial);
END^

-- -----------------------------------------------------------------------------
-- SP_DESVINCULAR_MATERIAL_PROVEEDOR
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_DESVINCULAR_MATERIAL_PROVEEDOR (
    pIdProveedor INTEGER,
    pIdMaterial  INTEGER
)
AS
BEGIN
    DELETE FROM Proveedores_has_Materiales
    WHERE Proveedores_idProveedor = :pIdProveedor
      AND Materiales_idMaterial   = :pIdMaterial;
END^

-- -----------------------------------------------------------------------------
-- SP_INSERTAR_MATERIAL
-- Crea un material en el catálogo. Si además viene con proveedor, vincula.
-- Para vincular proveedores adicionales, usar SP_VINCULAR_MATERIAL_PROVEEDOR.
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_INSERTAR_MATERIAL (
    pNombre       VARCHAR(150),
    pUnidadMedida VARCHAR(20),
    pDescripcion  BLOB SUB_TYPE TEXT
)
RETURNS (
    oIdMaterial INTEGER
)
AS
BEGIN
    INSERT INTO Materiales (Nombre, UnidadMedida, Descripcion)
    VALUES (:pNombre, :pUnidadMedida, :pDescripcion)
    RETURNING idMaterial INTO :oIdMaterial;

    SUSPEND;
END^

-- -----------------------------------------------------------------------------
-- SP_INSERTAR_OBRA
-- Crea una obra y la deja en estado "Solicitud recibida" (idEstadoObra = 1).
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_INSERTAR_OBRA (
    pIdCliente INTEGER,
    pNombre    VARCHAR(100),
    pDireccion BLOB SUB_TYPE TEXT
)
RETURNS (
    oIdObra INTEGER
)
AS
BEGIN
    INSERT INTO Obras (Clientes_idCliente, Nombre, Direccion, EstadosObra_idEstadoObra)
    VALUES (:pIdCliente, :pNombre, :pDireccion, 1)
    RETURNING idObra INTO :oIdObra;

    SUSPEND;
END^

-- -----------------------------------------------------------------------------
-- SP_CAMBIAR_ESTADO_OBRA
-- Valida que la transición de estado sea válida según la máquina de estados
-- del SRS (Apéndice B) antes de actualizar.
-- Retorna oExito=1 si se aplicó el cambio, oExito=0 con mensaje de error si no.
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_CAMBIAR_ESTADO_OBRA (
    pIdObra          INTEGER,
    pNuevoEstado     INTEGER   -- idEstadoObra destino
)
RETURNS (
    oExito   SMALLINT,
    oMensaje VARCHAR(200)
)
AS
    DECLARE VARIABLE vEstadoActual INTEGER;
    DECLARE VARIABLE vTransicionValida SMALLINT;
BEGIN
    SELECT EstadosObra_idEstadoObra FROM Obras WHERE idObra = :pIdObra
    INTO :vEstadoActual;

    IF (vEstadoActual IS NULL) THEN
    BEGIN
        oExito   = 0;
        oMensaje = 'Obra no encontrada.';
        SUSPEND;
        EXIT;
    END

    -- Validar transiciones permitidas (según Apéndice B del SRS)
    -- Estado 1=Solicitud recibida, 2=Levantamiento pendiente, 3=En fabricacion,
    -- 4=Instalacion programada, 5=Instalado, 6=Garantia, 7=Finalizado
    vTransicionValida = 0;

    IF (vEstadoActual = 1 AND pNuevoEstado = 2) THEN vTransicionValida = 1;
    IF (vEstadoActual = 2 AND pNuevoEstado = 3) THEN vTransicionValida = 1;
    IF (vEstadoActual = 3 AND pNuevoEstado = 4) THEN vTransicionValida = 1;
    IF (vEstadoActual = 4 AND pNuevoEstado = 5) THEN vTransicionValida = 1;
    IF (vEstadoActual = 5 AND pNuevoEstado = 6) THEN vTransicionValida = 1;
    IF (vEstadoActual = 5 AND pNuevoEstado = 7) THEN vTransicionValida = 1;
    IF (vEstadoActual = 6 AND pNuevoEstado = 7) THEN vTransicionValida = 1;

    IF (vTransicionValida = 0) THEN
    BEGIN
        oExito   = 0;
        oMensaje = 'Transición de estado no permitida del estado '
                   || CAST(vEstadoActual AS VARCHAR(3)) || ' al '
                   || CAST(pNuevoEstado AS VARCHAR(3)) || '.';
        SUSPEND;
        EXIT;
    END

    -- La transición es válida; el trigger AU de Obras se encargará de auditar
    UPDATE Obras
    SET EstadosObra_idEstadoObra = :pNuevoEstado
    WHERE idObra = :pIdObra;

    oExito   = 1;
    oMensaje = 'Estado actualizado correctamente.';
    SUSPEND;
END^

-- -----------------------------------------------------------------------------
-- SP_ASIGNAR_TRABAJADOR_OBRA
-- Registra la asignación de un trabajador a una etapa de una obra.
-- No lanza error si ya existe; agrega una nueva asignación (histórico).
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_ASIGNAR_TRABAJADOR_OBRA (
    pIdObra        INTEGER,
    pIdTrabajador  INTEGER,
    pIdEstadoObra  INTEGER
)
RETURNS (
    oIdDetalleAsignacion INTEGER
)
AS
BEGIN
    INSERT INTO Obras_has_Trabajadores (Obras_idObra, Trabajadores_idTrabajador, EstadosObra_idEstadoObra)
    VALUES (:pIdObra, :pIdTrabajador, :pIdEstadoObra)
    RETURNING idDetalleAsignacion INTO :oIdDetalleAsignacion;

    SUSPEND;
END^

-- -----------------------------------------------------------------------------
-- SP_REGISTRAR_PAGO
-- Registra un pago asociado a una obra.
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_REGISTRAR_PAGO (
    pIdObra        INTEGER,
    pIdTipoPago    INTEGER,
    pIdTrabajador  INTEGER,
    pIdEstadoObra  INTEGER,
    pMonto         DECIMAL(10,2),
    pIdFormaPago   INTEGER
)
RETURNS (
    oIdDetallePago INTEGER
)
AS
BEGIN
    INSERT INTO DetallesPagos
        (Obras_idObra, TiposPago_idTipoPago, Trabajadores_idTrabajador,
         EstadosObra_idEstadoObra, Monto, FormasPago_idFormaPago)
    VALUES
        (:pIdObra, :pIdTipoPago, :pIdTrabajador,
         :pIdEstadoObra, :pMonto, :pIdFormaPago)
    RETURNING idDetallePago INTO :oIdDetallePago;

    SUSPEND;
END^

-- -----------------------------------------------------------------------------
-- SP_REGISTRAR_COMPRA_COMPLETA
-- Crea el encabezado de compra y un detalle en una sola transacción.
-- Para múltiples líneas de detalle, el backend llama SP_AGREGAR_DETALLE_COMPRA
-- con el idCompra retornado.
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_REGISTRAR_COMPRA_COMPLETA (
    pIdTrabajador  INTEGER,
    pNotas         BLOB SUB_TYPE TEXT,
    pIdProveedor   INTEGER,
    pIdMaterial    INTEGER,
    pCantidad      DECIMAL(10,2),
    pMedida        VARCHAR(20)
)
RETURNS (
    oIdCompra        INTEGER,
    oIdDetalleCompra INTEGER
)
AS
BEGIN
    INSERT INTO Compras (Trabajadores_idTrabajador, Notas)
    VALUES (:pIdTrabajador, :pNotas)
    RETURNING idCompra INTO :oIdCompra;

    INSERT INTO DetallesCompras
        (Compras_idCompra,
         Proveedores_has_Materiales_Proveedores_idProveedor,
         Proveedores_has_Materiales_Materiales_idMaterial,
         Cantidad, Medida)
    VALUES
        (:oIdCompra, :pIdProveedor, :pIdMaterial, :pCantidad, :pMedida)
    RETURNING idDetalleCompra INTO :oIdDetalleCompra;

    SUSPEND;
END^

-- -----------------------------------------------------------------------------
-- SP_AGREGAR_DETALLE_COMPRA
-- Agrega una línea de detalle a una compra ya creada.
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_AGREGAR_DETALLE_COMPRA (
    pIdCompra    INTEGER,
    pIdProveedor INTEGER,
    pIdMaterial  INTEGER,
    pCantidad    DECIMAL(10,2),
    pMedida      VARCHAR(20)
)
RETURNS (
    oIdDetalleCompra INTEGER
)
AS
BEGIN
    INSERT INTO DetallesCompras
        (Compras_idCompra,
         Proveedores_has_Materiales_Proveedores_idProveedor,
         Proveedores_has_Materiales_Materiales_idMaterial,
         Cantidad, Medida)
    VALUES
        (:pIdCompra, :pIdProveedor, :pIdMaterial, :pCantidad, :pMedida)
    RETURNING idDetalleCompra INTO :oIdDetalleCompra;

    SUSPEND;
END^

-- -----------------------------------------------------------------------------
-- SP_ABRIR_GARANTIA
-- Abre un reporte de garantía y actualiza el estado de la obra a "Garantia" (6).
-- Se ejecuta en una sola transacción: si falla alguna parte, rollback automático.
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_ABRIR_GARANTIA (
    pIdObra          INTEGER,
    pIdTrabajador    INTEGER,
    pDescripcion     BLOB SUB_TYPE TEXT
)
RETURNS (
    oIdGarantia INTEGER
)
AS
BEGIN
    -- Cambiar estado de la obra a "Garantia"
    UPDATE Obras
    SET EstadosObra_idEstadoObra = 6   -- Garantia
    WHERE idObra = :pIdObra
      AND EstadosObra_idEstadoObra = 5; -- Solo desde "Instalado"

    IF (ROW_COUNT = 0) THEN
        EXCEPTION;  -- Lanza excepción genérica; el backend captura y devuelve error

    INSERT INTO Garantias
        (Obras_idObra, Descripcion, Trabajadores_idTrabajador, EstadosGarantia_idEstadoGarantia)
    VALUES
        (:pIdObra, :pDescripcion, :pIdTrabajador, 1)  -- 1 = Reportada
    RETURNING idGarantia INTO :oIdGarantia;

    SUSPEND;
END^

-- -----------------------------------------------------------------------------
-- SP_CERRAR_GARANTIA
-- Marca la garantía como resuelta y opcionalmente cierra la obra.
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_CERRAR_GARANTIA (
    pIdGarantia          INTEGER,
    pDescripcionResolucion BLOB SUB_TYPE TEXT,
    pCerrarObra          SMALLINT  -- 1 = pasar obra a Finalizado
)
AS
    DECLARE VARIABLE vIdObra INTEGER;
BEGIN
    SELECT Obras_idObra FROM Garantias WHERE idGarantia = :pIdGarantia
    INTO :vIdObra;

    UPDATE Garantias
    SET EstadosGarantia_idEstadoGarantia = 3,     -- Resuelta
        DescripcionResolucion             = :pDescripcionResolucion
    WHERE idGarantia = :pIdGarantia;

    IF (pCerrarObra = 1) THEN
    BEGIN
        -- Solo cierra si TODAS las garantías de la obra están resueltas
        UPDATE Obras
        SET EstadosObra_idEstadoObra = 7   -- Finalizado
        WHERE idObra = :vIdObra
          AND NOT EXISTS (
              SELECT 1 FROM Garantias
              WHERE Obras_idObra = :vIdObra
                AND EstadosGarantia_idEstadoGarantia <> 3  -- Distintas de Resuelta
                AND Activo = TRUE
          );
    END
END^

-- -----------------------------------------------------------------------------
-- SP_OTORGAR_PERMISOS_OBRA
-- Otorga múltiples permisos a un trabajador en una obra de una sola llamada.
-- pListaPermisos: lista de idCampoPermiso separados por coma, ej: '1,2,5'
-- NOTA: Firebird 5 no tiene split nativo; se usa una alternativa con EXECUTE BLOCK
-- o se itera desde Node. La versión recomendada es iterar desde Node llamando
-- SP_OTORGAR_PERMISO_OBRA por cada campo. Este SP maneja uno a la vez.
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_OTORGAR_PERMISO_OBRA (
    pIdObra          INTEGER,
    pIdTrabajador    INTEGER,
    pIdCampoPermiso  INTEGER
)
AS
BEGIN
    -- UPDATE OR INSERT para idempotencia (no falla si ya existe)
    UPDATE OR INSERT INTO PermisosGranularesObras
        (CamposPermiso_idCampoPermiso, Obras_idObra, Trabajadores_idTrabajador)
    VALUES
        (:pIdCampoPermiso, :pIdObra, :pIdTrabajador)
    MATCHING (CamposPermiso_idCampoPermiso, Obras_idObra, Trabajadores_idTrabajador);
END^

-- -----------------------------------------------------------------------------
-- SP_REVOCAR_PERMISO_OBRA
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_REVOCAR_PERMISO_OBRA (
    pIdObra          INTEGER,
    pIdTrabajador    INTEGER,
    pIdCampoPermiso  INTEGER
)
AS
BEGIN
    DELETE FROM PermisosGranularesObras
    WHERE CamposPermiso_idCampoPermiso = :pIdCampoPermiso
      AND Obras_idObra                 = :pIdObra
      AND Trabajadores_idTrabajador    = :pIdTrabajador;
END^

-- -----------------------------------------------------------------------------
-- SP_INSERTAR_AUDITORIA_DETALLE
-- Llamado desde Node para insertar detalles de auditoría de campos específicos
-- cuando la comparación se hace en JavaScript (tu enfoque preferido).
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_INSERTAR_AUDITORIA_DETALLE (
    pIdAuditoria  INTEGER,
    pCampo        VARCHAR(50),
    pValorAnterior BLOB SUB_TYPE TEXT,
    pValorNuevo   BLOB SUB_TYPE TEXT
)
AS
BEGIN
    INSERT INTO AuditoriasDetalles (Auditorias_idAuditoria, Campo, ValorAnterior, ValorNuevo)
    VALUES (:pIdAuditoria, :pCampo, :pValorAnterior, :pValorNuevo);
END^

-- -----------------------------------------------------------------------------
-- SP_INSERTAR_AUDITORIA
-- Llamado desde Node para registrar la cabecera de auditoría y retornar el ID,
-- que luego se usa para insertar los detalles con SP_INSERTAR_AUDITORIA_DETALLE.
-- -----------------------------------------------------------------------------
CREATE OR ALTER PROCEDURE SP_INSERTAR_AUDITORIA (
    pIdTrabajador    INTEGER,
    pTabla           VARCHAR(50),
    pAccion          VARCHAR(20),
    pDescripcion     BLOB SUB_TYPE TEXT,
    pRegistroAfectado VARCHAR(50)
)
RETURNS (
    oIdAuditoria INTEGER
)
AS
BEGIN
    INSERT INTO Auditorias (Trabajadores_idTrabajador, Tabla, Accion, Descripcion, RegistroAfectado)
    VALUES (:pIdTrabajador, :pTabla, :pAccion, :pDescripcion, :pRegistroAfectado)
    RETURNING idAuditoria INTO :oIdAuditoria;

    SUSPEND;
END^

SET TERM ;^


-- =============================================================================
-- SECCIÓN 5: VISTAS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- VW_OBRAS_KANBAN
-- Vista principal para el tablero kanban del dashboard (RF-01, RF-28).
-- Retorna cada obra activa con su estado, cliente y trabajadores asignados.
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_OBRAS_KANBAN AS
SELECT
    o.idObra,
    o.Nombre                    AS NombreObra,
    o.FechaUltimaActualizacion,
    o.FechaCreacion,
    c.idCliente,
    c.NombreCompleto            AS NombreCliente,
    c.Telefono                  AS TelefonoCliente,
    e.idEstadoObra,
    e.Nombre                    AS EstadoObra,
    e.Orden                     AS OrdenEstado
FROM Obras o
JOIN Clientes c ON c.idCliente = o.Clientes_idCliente
JOIN EstadosObra e ON e.idEstadoObra = o.EstadosObra_idEstadoObra
WHERE o.Activo = TRUE
  AND c.Activo = TRUE;

-- -----------------------------------------------------------------------------
-- VW_INDICADORES_DASHBOARD
-- Contadores por estado para la sección de resumen del dashboard (RF-28).
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_INDICADORES_DASHBOARD AS
SELECT
    e.Nombre                    AS EstadoObra,
    e.Orden,
    COUNT(o.idObra)             AS TotalObras
FROM EstadosObra e
LEFT JOIN Obras o ON o.EstadosObra_idEstadoObra = e.idEstadoObra
                 AND o.Activo = TRUE
GROUP BY e.idEstadoObra, e.Nombre, e.Orden;

-- -----------------------------------------------------------------------------
-- VW_CLIENTES_CON_OBRAS
-- Lista de clientes con conteo de obras activas (RF-03, RF-04, RF-05).
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_CLIENTES_CON_OBRAS AS
SELECT
    c.idCliente,
    c.NombreCompleto,
    c.Telefono,
    c.Correo,
    c.RFC,
    c.Activo,
    CASE WHEN c.RFC IS NOT NULL THEN TRUE ELSE FALSE END  AS TieneDatosFiscales,
    COUNT(o.idObra)                                        AS TotalObrasActivas
FROM Clientes c
LEFT JOIN Obras o ON o.Clientes_idCliente = c.idCliente
                 AND o.Activo = TRUE
                 AND o.EstadosObra_idEstadoObra < 7  -- Excluir Finalizadas
GROUP BY c.idCliente, c.NombreCompleto, c.Telefono, c.Correo, c.RFC, c.Activo;

-- -----------------------------------------------------------------------------
-- VW_DETALLE_OBRA
-- Vista completa de una obra con cliente, estado y datos de trabajadores
-- asignados en el estado actual (RF-07, RF-15).
-- El backend filtra por idObra en la WHERE.
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_DETALLE_OBRA AS
SELECT
    o.idObra,
    o.Nombre                        AS NombreObra,
    o.Direccion                     AS DireccionObra,
    o.FechaCreacion,
    o.FechaUltimaActualizacion,
    o.Activo,
    e.idEstadoObra,
    e.Nombre                        AS EstadoObra,
    e.Orden                         AS OrdenEstado,
    c.idCliente,
    c.NombreCompleto                AS NombreCliente,
    c.Telefono                      AS TelefonoCliente,
    c.Correo                        AS CorreoCliente,
    c.Direccion                     AS DireccionCliente,
    c.RFC,
    c.Activo                        AS ClienteActivo
FROM Obras o
JOIN Clientes c ON c.idCliente = o.Clientes_idCliente
JOIN EstadosObra e ON e.idEstadoObra = o.EstadosObra_idEstadoObra;

-- -----------------------------------------------------------------------------
-- VW_TRABAJADORES_POR_OBRA
-- Lista de trabajadores asignados a una obra por etapa.
-- El backend filtra por Obras_idObra.
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_TRABAJADORES_POR_OBRA AS
SELECT
    oht.Obras_idObra,
    oht.idDetalleAsignacion,
    oht.FechaAsignacion,
    e.idEstadoObra,
    e.Nombre            AS EstadoObra,
    t.idTrabajador,
    t.NombreCompleto    AS NombreTrabajador,
    t.NombreUsuario,
    t.Telefono          AS TelefonoTrabajador,
    t.Activo            AS TrabajadorActivo
FROM Obras_has_Trabajadores oht
JOIN Trabajadores t  ON t.idTrabajador  = oht.Trabajadores_idTrabajador
JOIN EstadosObra  e  ON e.idEstadoObra  = oht.EstadosObra_idEstadoObra;

-- -----------------------------------------------------------------------------
-- VW_MATERIALES_POR_OBRA
-- Lista de materiales requeridos para una obra (RF-16).
-- El backend filtra por Obras_idObra.
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_MATERIALES_POR_OBRA AS
SELECT
    ohm.Obras_idObra,
    m.idMaterial,
    m.Nombre            AS NombreMaterial,
    m.UnidadMedida,
    m.Descripcion       AS DescripcionMaterial,
    ohm.Cantidad,
    ohm.Medida,
    ohm.Notas
FROM Obras_has_Materiales ohm
JOIN Materiales m ON m.idMaterial = ohm.Materiales_idMaterial
WHERE m.Activo = TRUE;

-- -----------------------------------------------------------------------------
-- VW_CATALOGO_PROVEEDORES_MATERIALES
-- Catálogo completo de materiales con sus proveedores y precios (RF-27, M6).
-- Útil para la pantalla de compras: el backend filtra por proveedor o material.
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_CATALOGO_PROVEEDORES_MATERIALES AS
SELECT
    p.idProveedor,
    p.Nombre            AS NombreProveedor,
    p.Direccion         AS DireccionProveedor,
    p.Telefono          AS TelefonoProveedor,
    p.Correo            AS CorreoProveedor,
    p.Notas             AS NotasProveedor,
    p.Activo            AS ProveedorActivo,
    m.idMaterial,
    m.Nombre            AS NombreMaterial,
    m.UnidadMedida,
    m.Descripcion       AS DescripcionMaterial,
    m.Activo            AS MaterialActivo,
    phm.PrecioUnitario,
    phm.Notas           AS NotasVinculo
FROM Proveedores_has_Materiales phm
JOIN Proveedores p ON p.idProveedor = phm.Proveedores_idProveedor
JOIN Materiales  m ON m.idMaterial  = phm.Materiales_idMaterial
WHERE p.Activo = TRUE
  AND m.Activo = TRUE;

-- -----------------------------------------------------------------------------
-- VW_COMPRAS_CON_DETALLE
-- Vista de compras con sus líneas de detalle (proveedor + material + cantidad).
-- El backend filtra por idCompra o por Trabajadores_idTrabajador.
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_COMPRAS_CON_DETALLE AS
SELECT
    c.idCompra,
    c.FechaCompra,
    c.Notas             AS NotasCompra,
    c.Activo            AS CompraActiva,
    t.idTrabajador,
    t.NombreCompleto    AS NombreTrabajador,
    dc.idDetalleCompra,
    dc.Cantidad,
    dc.Medida,
    p.idProveedor,
    p.Nombre            AS NombreProveedor,
    p.Telefono          AS TelefonoProveedor,
    p.Direccion         AS DireccionProveedor,
    m.idMaterial,
    m.Nombre            AS NombreMaterial,
    m.UnidadMedida,
    phm.PrecioUnitario
FROM Compras c
JOIN Trabajadores t ON t.idTrabajador = c.Trabajadores_idTrabajador
JOIN DetallesCompras dc ON dc.Compras_idCompra = c.idCompra
JOIN Proveedores_has_Materiales phm
    ON phm.Proveedores_idProveedor = dc.Proveedores_has_Materiales_Proveedores_idProveedor
   AND phm.Materiales_idMaterial   = dc.Proveedores_has_Materiales_Materiales_idMaterial
JOIN Proveedores p ON p.idProveedor = phm.Proveedores_idProveedor
JOIN Materiales  m ON m.idMaterial  = phm.Materiales_idMaterial;

-- -----------------------------------------------------------------------------
-- VW_GARANTIAS_CON_OBRA
-- Vista de garantías con la info de la obra y cliente asociados (RF-22..RF-24).
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_GARANTIAS_CON_OBRA AS
SELECT
    g.idGarantia,
    g.Descripcion,
    g.DescripcionResolucion,
    g.FechaCreacion,
    g.FechaUltimaActualizacion,
    g.Activo            AS GarantiaActiva,
    eg.idEstadoGarantia,
    eg.Nombre           AS EstadoGarantia,
    o.idObra,
    o.Nombre            AS NombreObra,
    o.Direccion         AS DireccionObra,
    o.EstadosObra_idEstadoObra AS IdEstadoObra,
    c.idCliente,
    c.NombreCompleto    AS NombreCliente,
    c.Telefono          AS TelefonoCliente,
    t.idTrabajador,
    t.NombreCompleto    AS NombreResponsable
FROM Garantias g
JOIN EstadosGarantia eg ON eg.idEstadoGarantia = g.EstadosGarantia_idEstadoGarantia
JOIN Obras o            ON o.idObra             = g.Obras_idObra
JOIN Clientes c         ON c.idCliente          = o.Clientes_idCliente
JOIN Trabajadores t     ON t.idTrabajador        = g.Trabajadores_idTrabajador;

-- -----------------------------------------------------------------------------
-- VW_PAGOS_POR_OBRA
-- Historial de pagos de una obra con tipo, forma y trabajador que los registró.
-- El backend filtra por Obras_idObra. Solo visible para el propietario.
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_PAGOS_POR_OBRA AS
SELECT
    dp.idDetallePago,
    dp.Obras_idObra,
    dp.FechaRegistro,
    dp.Monto,
    tp.Nombre           AS TipoPago,
    fp.Nombre           AS FormaPago,
    e.Nombre            AS EstadoObraAlPago,
    t.NombreCompleto    AS TrabajadorQueRegistro
FROM DetallesPagos dp
JOIN TiposPago  tp ON tp.idTipoPago  = dp.TiposPago_idTipoPago
JOIN FormasPago fp ON fp.idFormaPago = dp.FormasPago_idFormaPago
JOIN EstadosObra e ON e.idEstadoObra = dp.EstadosObra_idEstadoObra
JOIN Trabajadores t ON t.idTrabajador = dp.Trabajadores_idTrabajador;

-- -----------------------------------------------------------------------------
-- VW_PERMISOS_TRABAJADOR_OBRA
-- Lista los permisos granulares de un trabajador en una obra.
-- El backend filtra por (Obras_idObra, Trabajadores_idTrabajador).
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_PERMISOS_TRABAJADOR_OBRA AS
SELECT
    pgo.idPermisoGranularObra,
    pgo.Obras_idObra,
    pgo.Trabajadores_idTrabajador,
    cp.idCampoPermiso,
    cp.NombreCampo,
    cp.Descripcion      AS DescripcionPermiso
FROM PermisosGranularesObras pgo
JOIN CamposPermiso cp ON cp.idCampoPermiso = pgo.CamposPermiso_idCampoPermiso;

-- -----------------------------------------------------------------------------
-- VW_AUDITORIA_COMPLETA
-- Vista del historial de auditoría con detalles de campos para el módulo M11.
-- El backend filtra por rango de fechas, tabla o trabajador según RF-30.
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_AUDITORIA_COMPLETA AS
SELECT
    a.idAuditoria,
    a.Fecha,
    a.Tabla,
    a.Accion,
    a.Descripcion,
    a.RegistroAfectado,
    t.idTrabajador,
    t.NombreCompleto    AS NombreTrabajador,
    t.NombreUsuario,
    ad.idAuditoriaDetalle,
    ad.Campo,
    ad.ValorAnterior,
    ad.ValorNuevo
FROM Auditorias a
JOIN Trabajadores t ON t.idTrabajador = a.Trabajadores_idTrabajador
LEFT JOIN AuditoriasDetalles ad ON ad.Auditorias_idAuditoria = a.idAuditoria
ORDER BY a.Fecha DESC;

-- -----------------------------------------------------------------------------
-- VW_OBRAS_TRABAJADOR
-- Vista que el backend usa para la app móvil: muestra solo las obras asignadas
-- al trabajador en el estado activo. NO expone precios ni datos fiscales.
-- El backend filtra por Trabajadores_idTrabajador.
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_OBRAS_TRABAJADOR AS
SELECT DISTINCT
    oht.Trabajadores_idTrabajador,
    o.idObra,
    o.Nombre            AS NombreObra,
    e.idEstadoObra,
    e.Nombre            AS EstadoObra,
    oht.FechaAsignacion
FROM Obras_has_Trabajadores oht
JOIN Obras o      ON o.idObra        = oht.Obras_idObra
JOIN EstadosObra e ON e.idEstadoObra = o.EstadosObra_idEstadoObra
WHERE o.Activo = TRUE;

-- -----------------------------------------------------------------------------
-- VW_BUSQUEDA_GLOBAL
-- Vista para el buscador global (RF-29). El backend hace LIKE contra esta vista.
-- Unifica clientes, obras y proveedores en una sola tabla de resultados.
-- -----------------------------------------------------------------------------
CREATE OR ALTER VIEW VW_BUSQUEDA_GLOBAL AS
-- Clientes
SELECT
    'cliente'           AS TipoRegistro,
    c.idCliente         AS IdRegistro,
    c.NombreCompleto    AS TextoPrimario,
    c.Telefono          AS TextoSecundario,
    NULL                AS TextoTerciario
FROM Clientes c
WHERE c.Activo = TRUE

UNION ALL

-- Obras
SELECT
    'obra'              AS TipoRegistro,
    o.idObra            AS IdRegistro,
    o.Nombre            AS TextoPrimario,
    c.NombreCompleto    AS TextoSecundario,
    e.Nombre            AS TextoTerciario
FROM Obras o
JOIN Clientes c    ON c.idCliente  = o.Clientes_idCliente
JOIN EstadosObra e ON e.idEstadoObra = o.EstadosObra_idEstadoObra
WHERE o.Activo = TRUE

UNION ALL

-- Proveedores
SELECT
    'proveedor'         AS TipoRegistro,
    p.idProveedor       AS IdRegistro,
    p.Nombre            AS TextoPrimario,
    p.Telefono          AS TextoSecundario,
    p.Correo            AS TextoTerciario
FROM Proveedores p
WHERE p.Activo = TRUE;